# Type de stockage: "memory", "json", ou "gorm"
storage:
  type: "gorm"
  path: "contacts.db"

# Exemple pour stockage JSON:
# storage:
#   type: "json"
#   path: "contacts.json"

# Exemple pour stockage en mémoire (temporaire):
# storage:
#   type: "memory"
#   path: ""